name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker-build.yml'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate image name
        id: image
        run: |
          IMAGE_NAME=$(echo "${{ github.repository }}/cpp-dev" | tr '[:upper:]' '[:lower:]')
          echo "name=${IMAGE_NAME}" >> $GITHUB_OUTPUT
          echo "full_name=${{ env.REGISTRY }}/${IMAGE_NAME}" >> $GITHUB_OUTPUT

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.image.outputs.full_name }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Verify image
        run: |
          docker run --rm ${{ steps.image.outputs.full_name }}:latest bash -c "
            gcc-15 --version > /dev/null &&
            g++-15 --version > /dev/null &&
            clang-20 --version > /dev/null &&
            clang++-20 --version > /dev/null &&
            cmake --version > /dev/null &&
            ninja --version > /dev/null &&
            echo 'All tools verified successfully!'
          "
